Mounting

In [1]:
# 1. Mounting drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install --upgrade scikit-learn==1.5.1

In [ ]:
import sklearn
print(sklearn.__version__)

1.5.1


In [ ]:
# Pra Preprocessing Text
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

PREPROCESSING PER CATEGORY

In [ ]:
# 2.1 Preprocessing text Adult
import pandas as pd
import os
import re

def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()
        teks = re.sub(r'<[^>]*>', '', teks)
        teks = re.sub(r'http?://\S+ ?', '', teks)
        teks = re.sub(r'[^\w\s]', '', teks)
        teks = re.sub(r'[0-9]+', ' ', teks)
        teks = re.sub(r'[^\x00-\x7f]', '', teks)
        stop_words = stopwords.words('english') + \
                    stopwords.words('french') + \
                    stopwords.words('russian') + \
                    stopwords.words('indonesian')
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/Scrape/ADULT_TLS1.csv', lineterminator='\n', encoding='utf-8')
df['contents'] = df['contents'].apply(regeks)
print(df['contents'])

# Save DataFrame to a CSV file
output_folder = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro'  # Specify the directory where you want to save the CSV
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_file = os.path.join(output_folder, 'ADULT_PP.csv')
df.to_csv(output_file, index=False)

print(f'Data has been saved to {output_file}')


0      originally posted machetelanding word count pa...
1      originally posted lovemusicfashionflawless she...
2      originally posted wildeoscars word count pairi...
3      originally posted thedrxamsynopsis word count ...
4      get experienced future trunk giving girl first...
                             ...                        
826    aline acrobatic stunt special position adorabl...
827    th april photo multiple dick sucking httpssexy...
828    lady love mentally dating eddie munson paring ...
829    lady love mentally dating eddie munson origina...
830    lady love mentally dating eddie munson origina...
Name: contents, Length: 831, dtype: object
Data has been saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro/ADULT_PP.csv


In [ ]:
# 2.1 Preprocessing text Gambling
import pandas as pd
import os
import re

def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()
        teks = re.sub(r'<[^>]*>', '', teks)
        teks = re.sub(r'http?://\S+ ?', '', teks)
        teks = re.sub(r'[^\w\s]', '', teks)
        teks = re.sub(r'[0-9]+', ' ', teks)
        teks = re.sub(r'[^\x00-\x7f]', '', teks)
        stop_words = stopwords.words('english') + \
                    stopwords.words('french') + \
                    stopwords.words('russian') + \
                    stopwords.words('indonesian')
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/Scrape/Gambling_TL.csv', lineterminator='\n', encoding='utf-8')
df['contents'] = df['contents'].apply(regeks)
print(df['contents'])

# Save DataFrame to a CSV file
output_folder = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro'  # Specify the directory where you want to save the CSV
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_file = os.path.join(output_folder, 'Gambling_PP.csv')
df.to_csv(output_file, index=False)

print(f'Data has been saved to {output_file}')


0      improve user experience use cooky clicking lin...
1      get baht clash bonus also lucky spin spin win ...
2      net business ltd regent house bisazza street s...
3      dream casino founded year experience gambling ...
4      free casino game type free casino platform enj...
                             ...                        
958                                       wildzcasinotop
959                   percaya best online site indonesia
960    world casino directory casino guide gambling f...
961                  world poker tour online poker wptfr
962                                            affiliate
Name: contents, Length: 963, dtype: object
Data has been saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro/Gambling_PP.csv


In [ ]:
# 2.1 Preprocessing text Phishing
import pandas as pd
import os
import re

def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()
        teks = re.sub(r'<[^>]*>', '', teks)
        teks = re.sub(r'http?://\S+ ?', '', teks)
        teks = re.sub(r'[^\w\s]', '', teks)
        teks = re.sub(r'[0-9]+', ' ', teks)
        teks = re.sub(r'[^\x00-\x7f]', '', teks)
        stop_words = stopwords.words('english') + \
                    stopwords.words('french') + \
                    stopwords.words('russian') + \
                    stopwords.words('indonesian')
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/Scrape/PHISHING_TLS1.csv', lineterminator='\n', encoding='utf-8')
df['contents'] = df['contents'].apply(regeks)
print(df['contents'])

# Save DataFrame to a CSV file
output_folder = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro'  # Specify the directory where you want to save the CSV
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_file = os.path.join(output_folder, 'Phishing_PP.csv')
df.to_csv(output_file, index=False)

print(f'Data has been saved to {output_file}')


0      pomfsu file hosting site using pomf operated l...
1      domain name aamaz nfr sale price eur page crea...
2      financial success start ab financing solution ...
3      plot block th street anna nagar west chennai g...
4      add value supply chain superior assembly subas...
                             ...                        
572    buy domain name dancom youre automatically cov...
573    old gloucester street london united kingdom wc...
574    domain name zsmk sale price usd page created d...
575    domain name zurosportfr sale price eur page cr...
576    everything need work together one place explor...
Name: contents, Length: 577, dtype: object
Data has been saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro/Phishing_PP.csv


In [ ]:
# 2.1 Preprocessing text Whitelist
import pandas as pd
import os
import re

def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()
        teks = re.sub(r'<[^>]*>', '', teks)
        teks = re.sub(r'http?://\S+ ?', '', teks)
        teks = re.sub(r'[^\w\s]', '', teks)
        teks = re.sub(r'[0-9]+', ' ', teks)
        teks = re.sub(r'[^\x00-\x7f]', '', teks)
        stop_words = stopwords.words('english') + \
                    stopwords.words('french') + \
                    stopwords.words('russian') + \
                    stopwords.words('indonesian')
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/Scrape/Whitelist_TL.csv', lineterminator='\n', encoding='utf-8')
df['contents'] = df['contents'].apply(regeks)
print(df['contents'])

# Save DataFrame to a CSV file
output_folder = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro'  # Specify the directory where you want to save the CSV
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

output_file = os.path.join(output_folder, 'Whitelist_PP.csv')
df.to_csv(output_file, index=False)

print(f'Data has been saved to {output_file}')

0      one day prince come wellknown song disney univ...
1                                              copyright
2      yonatan klinger lawyer master degree business ...
3      many ghost left lingering city remember left d...
4                                                   xcom
                             ...                        
535    wouldnt surprised know average indonesian spen...
536    written josef petrk tldr auth nette extension ...
537    contact u zaptank consulting provides followin...
538    movie tv serial reality show related informati...
539    blog tudes pioneering firm seamlessly merges c...
Name: contents, Length: 540, dtype: object
Data has been saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/PrePro/Whitelist_PP.csv


**FEATURE EXTRACTION**

In [ ]:
# 4. Feature Extraction
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib
import os

# Path ke file CSV
file_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/Dataset_Labelsv2.csv'
df = pd.read_csv(file_path)

# Membuat objek TfidfVectorizer dengan parameter tertentu
tfidf = TfidfVectorizer(
    sublinear_tf=True,   # Menggunakan sublinear tf scaling
    min_df=5,            # Meminimalkan frekuensi dokumen untuk setiap fitur
    norm='l2',           # Normalisasi L2 pada vektor
    encoding='latin-1',  # Encoding teks
    ngram_range=(1, 2),  # Menggunakan unigram dan bigram
)

# Mengisi nilai kosong pada kolom 'contents' dengan string kosong ' '
Ex = df['contents'].fillna(' ')

# Menyesuaikan dan mengubah teks menjadi fitur TF-IDF
features = tfidf.fit_transform(Ex).toarray()

# Menyiapkan label dari kolom 'category'
labels = df['category']

# Gabungkan fitur dan label ke dalam DataFrame
df_features = pd.DataFrame(features)
df_features['label'] = labels.values

# Path directory untuk menyimpan file
save_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/'

# Pastikan directory sudah ada, jika belum maka dibuat
os.makedirs(save_path, exist_ok=True)

# Menyimpan fitur dan label ke dalam file CSV
csv_path = os.path.join(save_path, 'Dataset_TFIDF.csv')
df_features.to_csv(csv_path, index=False)
print(f'Fitur dan label disimpan dalam format CSV di: {csv_path}')

# Menyimpan objek TfidfVectorizer dan fitur ke dalam file pkl
pkl_path = os.path.join(save_path, 'Data_TFIDF.pkl')
joblib.dump((tfidf, features, labels), pkl_path)
print(f'Objek TfidfVectorizer dan fitur disimpan dalam format PKL di: {pkl_path}')

print(f'Bentuk fitur: {features.shape}')

Fitur dan label disimpan dalam format CSV di: /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Dataset_TFIDF.csv
Objek TfidfVectorizer dan fitur disimpan dalam format PKL di: /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl
Bentuk fitur: (2911, 36534)


**TRAINING DATA**

In [ ]:
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier

# Load dataset from .pkl file
pkl_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
tfidf, features, labels = joblib.load(pkl_path)

# Define models
models = [
    MultinomialNB(),
    GaussianNB(),
    KNeighborsClassifier(n_neighbors=25),
    SVC(kernel='linear', C=1),
    OneVsRestClassifier(LinearSVC(class_weight="balanced"))
]

# Cross-validation setup
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []

for model in models:
    model_name = model.__class__.__name__
    accuracies = cross_val_score(model, features, labels, scoring='accuracy', cv=CV)
    for fold_idx, accuracy in enumerate(accuracies):
        entries.append((model_name, fold_idx, accuracy))

cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])


# Find the model with the best average accuracy
mean_accuracies = cv_df.groupby('model_name').accuracy.mean()
best_model_name = mean_accuracies.idxmax()
best_model_accuracy = mean_accuracies.max()

print(f"Best Model: {best_model_name} with Accuracy: {best_model_accuracy:.2%}")

# Train the best model on the entire dataset
for model in models:
    if model.__class__.__name__ == best_model_name:
        best_model = model
        best_model.fit(features, labels)
        break

              model_name  fold_idx  accuracy
0          MultinomialNB         0  0.720412
1          MultinomialNB         1  0.725086
2          MultinomialNB         2  0.671821
3          MultinomialNB         3  0.714777
4          MultinomialNB         4  0.697595
5             GaussianNB         0  0.691252
6             GaussianNB         1  0.697595
7             GaussianNB         2  0.658076
8             GaussianNB         3  0.733677
9             GaussianNB         4  0.639175
10  KNeighborsClassifier         0  0.296741
11  KNeighborsClassifier         1  0.310997
12  KNeighborsClassifier         2  0.298969
13  KNeighborsClassifier         3  0.307560
14  KNeighborsClassifier         4  0.286942
15                   SVC         0  0.838765
16                   SVC         1  0.836770
17                   SVC         2  0.823024
18                   SVC         3  0.845361
19                   SVC         4  0.768041
20   OneVsRestClassifier         0  0.835334
21   OneVs

**TRAINING DATA + MODEL TERBAIK DI BUAT FILE PICKLE. DATASET TFIDF VERSI PICKLE**

In [ ]:
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier

# Load dataset from .pkl file
pkl_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
tfidf, features, labels = joblib.load(pkl_path)

# Define models
models = [
    MultinomialNB(),
    GaussianNB(),
    KNeighborsClassifier(n_neighbors=25),
    SVC(kernel='linear', C=1),
    OneVsRestClassifier(LinearSVC(class_weight="balanced"))
]

# Cross-validation setup
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []

# Evaluate each model using cross-validation
for model in models:
    model_name = model.__class__.__name__
    accuracies = cross_val_score(model, features, labels, scoring='accuracy', cv=CV)
    for fold_idx, accuracy in enumerate(accuracies):
        entries.append((model_name, fold_idx, accuracy))

# Store the results in a DataFrame
cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])

# Calculate mean accuracies for each model
mean_accuracies = cv_df.groupby('model_name').accuracy.mean()

# Print mean accuracies for each model
print("Average Accuracy for each model:")
for model_name, accuracy in mean_accuracies.items():
    print(f"{model_name}: {accuracy:.2%}")

# Identify the best model
best_model_name = mean_accuracies.idxmax()
best_model_accuracy = mean_accuracies.max()

print(f"\nBest Model: {best_model_name} with Accuracy: {best_model_accuracy:.2%}")

# Train the best model on the entire dataset
for model in models:
    if model.__class__.__name__ == best_model_name:
        best_model = model
        best_model.fit(features, labels)
        break

# Hilangkan komentar dibawah ini jika ingin menyimpan file model .pkl
# # Simpan model terbaik sebagai file .pkl
# pkl_save_path = f'/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/{best_model_name}.pkl'
# joblib.dump(best_model, pkl_save_path)

# print(f"\nModel Telah disimpan di {pkl_save_path}")

Average Accuracy for each model:
GaussianNB: 68.40%
KNeighborsClassifier: 30.02%
MultinomialNB: 70.59%
OneVsRestClassifier: 81.07%
SVC: 82.24%

Best Model: SVC with Accuracy: 82.24%


In [ ]:
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset from .pkl file
pkl_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
tfidf, features, labels = joblib.load(pkl_path)

# Define models
models = [
    MultinomialNB(),
    GaussianNB(),
    KNeighborsClassifier(n_neighbors=25),
    SVC(kernel='linear', C=1),
    OneVsRestClassifier(LinearSVC(class_weight="balanced"))
]

# Cross-validation setup
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []

# Initialize a dictionary to store predictions and true labels
all_predictions = {}
all_labels = {}
# Evaluate each model using cross-validation
for model in models:
    model_name = model.__class__.__name__
    all_predictions[model_name] = []
    all_labels[model_name] = []
    for fold_idx in range(CV):
        # Split data into training and testing sets for this fold
        X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=1/CV, random_state=fold_idx)

        # Train the model on the training data
        model.fit(X_train, y_train)
        # Make predictions on the test data
        y_pred = model.predict(X_test)

        # Store predictions and true labels for this fold
        all_predictions[model_name].extend(y_pred)
        all_labels[model_name].extend(y_test)

        # Calculate and store accuracy for this fold (you can keep this part if you still need it)
        accuracy = accuracy_score(y_test, y_pred)
        entries.append((model_name, fold_idx, accuracy))

# Print mean accuracies for each model
print("Average Accuracy for each model:")
for model_name, accuracy in mean_accuracies.items():
    print(f"{model_name}: {accuracy:.2%}")

# Identify the best model
best_model_name = mean_accuracies.idxmax()
best_model_accuracy = mean_accuracies.max()

print(f"\nBest Model: {best_model_name} with Accuracy: {best_model_accuracy:.2%}")

# Train the best model on the entire dataset
for model in models:
    if model.__class__.__name__ == best_model_name:
        best_model = model
        best_model.fit(features, labels)
        break

# Make predictions on the entire dataset using the best model
predictions = best_model.predict(features)

# Generate and print classification reports for all models
for model_name in all_predictions:
    print(f"\nClassification Report for {model_name}:\n")
    print(classification_report(all_labels[model_name], all_predictions[model_name]))

# # Save the best model as a .pkl file
# pkl_save_path = f'/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/{best_model_name}.pkl'
# joblib.dump(best_model, pkl_save_path)

# print(f"\nModel saved to {pkl_save_path}")

Average Accuracy for each model:
GaussianNB: 68.40%
KNeighborsClassifier: 30.02%
MultinomialNB: 70.59%
OneVsRestClassifier: 81.07%
SVC: 82.24%

Best Model: SVC with Accuracy: 82.24%

Classification Report for MultinomialNB:

              precision    recall  f1-score   support

    Gambling       0.65      0.99      0.79       978
    Phishing       0.86      0.49      0.63       535
        Porn       0.90      0.89      0.90       857
   Whitelist       0.84      0.44      0.58       545

    accuracy                           0.77      2915
   macro avg       0.82      0.70      0.72      2915
weighted avg       0.80      0.77      0.75      2915


Classification Report for GaussianNB:

              precision    recall  f1-score   support

    Gambling       0.77      0.90      0.83       978
    Phishing       0.45      0.48      0.46       535
        Porn       0.93      0.87      0.90       857
   Whitelist       0.64      0.50      0.56       545

    accuracy                

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import pandas as pd
import joblib
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Load dataset from .pkl file
pkl_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
tfidf, features, labels = joblib.load(pkl_path)

# Define models
models = [
    MultinomialNB(),
    GaussianNB(),
    KNeighborsClassifier(n_neighbors=25),
    SVC(kernel='linear', C=1),
    OneVsRestClassifier(LinearSVC(class_weight="balanced"))
]

# Cross-validation setup
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []

# Initialize a dictionary to store predictions and true labels
all_predictions = {}
all_labels = {}

# Evaluate each model using cross-validation and save them
for model in models:
    model_name = model.__class__.__name__
    all_predictions[model_name] = []
    all_labels[model_name] = []

    # Train the model on the entire dataset (outside the cross-validation loop)
    model.fit(features, labels)

    # Save the trained model
    pkl_save_path = f'/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/{model_name}.pkl'
    joblib.dump(model, pkl_save_path)
    print(f"\nModel {model_name} saved to {pkl_save_path}")

    accuracies = cross_val_score(model, features, labels, scoring='accuracy', cv=CV)
    for fold_idx, accuracy in enumerate(accuracies):
        entries.append((model_name, fold_idx, accuracy))

    # Split data into training and testing sets for this fold (INSIDE the cross-validation loop)
    # X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=1/CV, random_state=fold_idx)

    # # Make predictions on the test data (using the already trained model)
    # y_pred = model.predict(X_test)

    # # Store predictions and true labels for this fold
    # all_predictions[model_name].extend(y_pred)
    # all_labels[model_name].extend(y_test)

    # # Calculate and store accuracy for this fold
    # accuracy = accuracy_score(y_test, y_pred)
    # entries.append((model_name, fold_idx, accuracy))

# Store the results in a DataFrame
cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])

# Calculate mean accuracies for each model
mean_accuracies = cv_df.groupby('model_name').accuracy.mean()

# Print mean accuracies for each model
print("Average Accuracy for each model:")
for model_name, accuracy in mean_accuracies.items():
    print(f"{model_name}: {accuracy:.2%}")



Model MultinomialNB saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/MultinomialNB.pkl

Model GaussianNB saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/GaussianNB.pkl

Model KNeighborsClassifier saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/KNeighborsClassifier.pkl

Model SVC saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl

Model OneVsRestClassifier saved to /content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/OneVsRestClassifier.pkl
Average Accuracy for each model:
GaussianNB: 68.40%
KNeighborsClassifier: 30.02%
MultinomialNB: 70.59%
OneVsRestClassifier: 81.07%
SVC: 82.24%

Classification Report for MultinomialNB:



ValueError: max() arg is an empty sequence

**TRAINING + CLASSIFICATION REPORT. DATASET TFIDF VERSI CSV**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
import joblib
import os

# Load the TF-IDF data from the CSV file
file_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Dataset_TFIDF.csv'
data = pd.read_csv(file_path)

# Drop rows with NaN values in labels or features
data = data.dropna(subset=['label'])
labels = data['label']
features = data.drop(columns=['label'])

# Fill NaN values in features (if any) with 0
features = features.fillna(0)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Convert string labels to numerical using LabelEncoder
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

# Initialize models
nb_model = MultinomialNB()
knn_model = KNeighborsClassifier(n_neighbors=5)
svm_model = SVC(kernel='linear')

# List of models and their names
models = [nb_model, knn_model, svm_model]
model_names = ['Naive Bayes', 'K-Nearest Neighbors', 'Support Vector Machine']

# Cross-validation with training
CV = 5
entries = []

best_model = None
best_accuracy = 0
best_model_name = ""

for model, model_name in zip(models, model_names):
    print(f"Evaluating {model_name} Model")
    accuracies = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=CV)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    print(f"Accuracy: {accuracy:.2%}") # Format as percentage
    print(classification_report(y_test, predictions, target_names=label_encoder.classes_, digits=2))

    # The following loop was indented incorrectly, causing the error.
    for fold_idx, acc in enumerate(accuracies):
        entries.append((model_name, fold_idx, acc))

    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_model = model
        best_model_name = model_name

cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])

print("\nCross-Validation Results:")
print(cv_df.groupby('model_name')['accuracy'].mean().apply(lambda x: "{:.2%}".format(x)))

Evaluating Naive Bayes Model
Accuracy: 76.84%
              precision    recall  f1-score   support

    Gambling       0.66      0.99      0.79       200
    Phishing       0.90      0.46      0.61       112
        Porn       0.93      0.90      0.91       169
   Whitelist       0.74      0.45      0.56       102

    accuracy                           0.77       583
   macro avg       0.81      0.70      0.72       583
weighted avg       0.80      0.77      0.75       583

Evaluating K-Nearest Neighbors Model
Accuracy: 26.24%
              precision    recall  f1-score   support

    Gambling       1.00      0.07      0.13       200
    Phishing       0.88      0.06      0.12       112
        Porn       0.97      0.18      0.30       169
   Whitelist       0.19      1.00      0.32       102

    accuracy                           0.26       583
   macro avg       0.76      0.33      0.22       583
weighted avg       0.83      0.26      0.21       583

Evaluating Support Vector Mach

**BACA MODEL PICKLE**

In [ ]:
import joblib

# Path to the SVC model file
svc_pkl_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl'

# Load the SVC model
svc_model = joblib.load(svc_pkl_path)

# Inspect the model
print("SVC Model details:")
print(svc_model)

# Access and print some relevant attributes
print("\nModel's support vectors:")
print(svc_model.support_vectors_[:5])  # Print first 5 support vectors

print("\nModel's coefficients:")
print(svc_model.coef_[:5])  # Print first 5 coefficients (for linear kernel)

print("\nModel's intercept:")
print(svc_model.intercept_)  # Print the intercept

print("\nModel's classes:")
print(svc_model.classes_)  # Print the classes

# If needed, check other attributes of the SVC model
# For example, if it's a linear SVC, you can access the coefficients and support vectors
if hasattr(svc_model, 'coef_'):
    print("\nModel's feature names (if available):")
    try:
        feature_names = vectorizer.get_feature_names_out()
        print(feature_names[:10])  # Print first 10 feature names
    except:
        print("Feature names are not available.")
else:
    print("Model does not have coef_ attribute, possibly a non-linear SVC.")


SVC Model details:
SVC(C=1, kernel='linear')

Model's support vectors:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Model's coefficients:
[[ 0.11491493  0.06290193  0.02221418 ... -0.02634481  0.
   0.        ]
 [ 0.05189887  0.10458166  0.         ...  0.09404513  0.
   0.        ]
 [ 0.02399365  0.0979533   0.0383275  ...  0.12689767 -0.00187289
  -0.00194232]
 [ 0.          0.          0.         ...  0.06324726  0.
   0.        ]
 [-0.06704176  0.05314664  0.         ...  0.235968   -0.00990096
  -0.00709272]]

Model's intercept:
[-0.32404764 -0.4854843  -0.46750652 -0.28010752 -0.11610672  0.15003996]

Model's classes:
['Gambling' 'Phishing' 'Porn' 'Whitelist']

Model's feature names (if available):
['aa' 'aaa' 'aams' 'aaron' 'ab' 'abandon' 'abandoned' 'abandoned building'
 'abandoned soon' 'abandoning']


In [ ]:
import joblib  # Use joblib for loading models, especially scikit-learn models

# Path to the .pkl file in your Google Drive
data = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl'

# Load model using joblib
model = joblib.load(data)

In [ ]:
print(model.classes_)  # Menampilkan kelas-kelas yang ada
print(model.support_vectors_)

['Gambling' 'Phishing' 'Porn' 'Whitelist']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


TEST MODEL

In [ ]:
# prompt: prediksi data tfidf dan model. inputnya adalah URL, berarti dia harus scrape berikan full code lengkap

from google.colab import drive
import sklearn
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import pandas as pd
import os
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np
import joblib  # Use joblib for loading models, especially scikit-learn models
import requests
from bs4 import BeautifulSoup
import time
from IPython.display import display, HTML
from IPython.display import HTML

# 1. Memuat data TF-IDF dan model yang sudah dilatih
# Path ke data TF-IDF dan model terbaik Anda
tfidf_data_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
model_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl'

# Muat data TF-IDF dan model menggunakan joblib
tfidf, features, labels = joblib.load(tfidf_data_path)
model = joblib.load(model_path)

# 2. Fungsi untuk pra-pemrosesan teks baru
def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()  # Ubah teks menjadi huruf kecil
        teks = re.sub(r'<[^>]*>', '', teks)  # Hapus tag HTML
        teks = re.sub(r'http?://\S+ ?', '', teks)  # Hapus URL
        teks = re.sub(r'[^\w\s]', '', teks)  # Hapus tanda baca
        teks = re.sub(r'[0-9]+', ' ', teks)  # Hapus angka
        teks = re.sub(r'[^\x00-\x7f]', '', teks)  # Hapus karakter non-ASCII

        # Gabungkan daftar stop words dari beberapa bahasa
        stop_words = stopwords.words('english') + \
                     stopwords.words('french') + \
                     stopwords.words('russian') + \
                     stopwords.words('indonesian')

        # Hapus stop words dan lakukan lemmatization
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

# 3. Fungsi untuk mengambil konten dari URL
def scrape_url(url):
    if not url.startswith("http://") and not url.startswith("https://"):
        url = "https://" + url  # Tambahkan https:// jika protokol tidak ditentukan

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'}
    for attempt in range(2):  # Coba hingga 2 kali
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()  # Pastikan permintaan berhasil
            return response.content
        except requests.exceptions.RequestException as e:
            print(f"Percobaan {attempt + 1} untuk {url} gagal dengan kesalahan: {e}. Mencoba lagi...")
            time.sleep(2)  # Tunggu 2 detik sebelum mencoba lagi
    return None

# 4. Masukkan URL untuk prediksi
url_to_predict = "bunghatta.ac.id"  # Ganti dengan URL yang ingin Anda prediksi

# 5. Ambil konten dari URL
content = scrape_url(url_to_predict)

if content is None:
    print(f"Gagal mengambil konten dari {url_to_predict}")
else:
    soup = BeautifulSoup(content, "html.parser")

    # Hapus semua kode JavaScript dan stylesheet
    for script in soup(["script", "style"]):
        script.extract()

    # Ekstrak konten teks dari halaman web
    text_content = soup.get_text(separator=' ')

    # 6. Pra-pemrosesan teks yang diambil
    processed_text = regeks(text_content)

    # 7. Transformasi teks yang sudah diproses menggunakan TF-IDF
    new_text_features = tfidf.transform([processed_text]).toarray()

    # 8. Lakukan prediksi
    prediction = model.predict(new_text_features)

    # 9. Dapatkan kategori yang diprediksi (dengan asumsi prediksi langsung berupa label kategori)
    predicted_category = prediction[0]

    # 10. Cetak hasil
    print(f"URL Terdeteksi untuk {url_to_predict}: {predicted_category}")


URL Terdeteksi untuk bunghatta.ac.id: Whitelist


In [ ]:
!pip install flask

In [ ]:
# prompt: buatkan flask, inputnya adalah URL. halaman utamanya adalah index.html, hasil prediksinya pada kolom kategori, seperti code prediksi sebelumnya. berikan code full lengkap

from flask import Flask, request, render_template
import joblib
import re
import requests
from bs4 import BeautifulSoup
import time
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

app = Flask(__name__)

# Load the TF-IDF vectorizer and trained model
tfidf_data_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
model_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl'
tfidf, _, _ = joblib.load(tfidf_data_path)
model = joblib.load(model_path)

# Preprocessing function
def regeks(teks):
    if isinstance(teks, str):
        teks = teks.lower()
        teks = re.sub(r'<[^>]*>', '', teks)
        teks = re.sub(r'http?://\S+ ?', '', teks)
        teks = re.sub(r'[^\w\s]', '', teks)
        teks = re.sub(r'[0-9]+', ' ', teks)
        teks = re.sub(r'[^\x00-\x7f]', '', teks)
        stop_words = stopwords.words('english') + \
                     stopwords.words('french') + \
                     stopwords.words('russian') + \
                     stopwords.words('indonesian')
        teks = ' '.join([word for word in teks.split() if word not in stop_words])
        lemmatizer = WordNetLemmatizer()
        teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
        return teks
    return teks

# Function to scrape content from URL
def scrape_url(url):
    if not url.startswith("http://") and not url.startswith("https://"):
        url = "https://" + url
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'}
    for attempt in range(2):
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()
            return response.content
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt + 1} for {url} failed with error: {e}. Retrying...")
            time.sleep(2)
    return None

# Route for the index page
@app.route('/')
def index():
    return render_template('index.html')

# Route to handle prediction requests
@app.route('/predict', methods=['POST'])
def predict():
    url = request.form['url']
    content = scrape_url(url)
    if content is None:
        return render_template('index.html', error=f"Failed to retrieve content from {url}")

    soup = BeautifulSoup(content, "html.parser")
    for script in soup(["script", "style"]):
        script.extract()
    text_content = soup.get_text(separator=' ')
    processed_text = regeks(text_content)
    new_text_features = tfidf_vectorizer.transform([processed_text]).toarray()
    prediction = model.predict(new_text_features)
    predicted_category = prediction[0]
    return render_template('index.html', prediction=predicted_category, url=url)

if __name__ == '__main__':
    app.run(debug=True)


 * Serving Flask app '__main__'
 * Debug mode: on


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat


In [ ]:
# # prompt: prediksi data tfidf dan model. berikan full code lengkap
# import sklearn
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import pandas as pd
# import os
# import re
# from sklearn.feature_extraction.text import TfidfVectorizer
# import joblib
# from sklearn.model_selection import cross_val_score
# from sklearn.naive_bayes import MultinomialNB, GaussianNB
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.svm import SVC, LinearSVC
# from sklearn.multiclass import OneVsRestClassifier
# from sklearn.model_selection import train_test_split, cross_val_score
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.svm import SVC
# from sklearn.metrics import classification_report, accuracy_score
# from sklearn.preprocessing import LabelEncoder
# import numpy as np
# import joblib  # Use joblib for loading models, especially scikit-learn models


# # 2. Load the TF-IDF data and the trained model
# tfidf_data_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/Data_TFIDF.pkl'
# model_path = '/content/drive/MyDrive/Colab Notebooks/Web Scraping Reihan/Klasifikasi/Versi 2/TFIDF/SVC.pkl'  # Path to your best model

# tfidf, features, labels = joblib.load(tfidf_data_path)
# model = joblib.load(model_path)

# # 3. Function for preprocessing new text
# def regeks(teks):
#     if isinstance(teks, str):
#         teks = teks.lower()
#         teks = re.sub(r'<[^>]*>', '', teks)
#         teks = re.sub(r'http?://\S+ ?', '', teks)
#         teks = re.sub(r'[^\w\s]', '', teks)
#         teks = re.sub(r'[0-9]+', ' ', teks)
#         teks = re.sub(r'[^\x00-\x7f]', '', teks)
#         stop_words = stopwords.words('english') + \
#                     stopwords.words('french') + \
#                     stopwords.words('russian') + \
#                     stopwords.words('indonesian')
#         teks = ' '.join([word for word in teks.split() if word not in stop_words])
#         lemmatizer = WordNetLemmatizer()
#         teks = ' '.join([lemmatizer.lemmatize(word) for word in teks.split()])
#         return teks
#     return teks

# # 4. Input new text for prediction
# new_text = "Originally posted by machetelanding  Word count: 669 Pairing: Ash Williams x reader Warnings: Age play, adult themes, smut  “Come to Daddy!” Ash coaxes. You head over to him and sit on his lap. Sure, he’s not the most handsome or in shape guy, but for someone in his late 50’s, you are enamored with him. He makes you laugh, buys you little gifts, pleases you well and…he accepts your kink. “Hi Daddy. What are we going to do today?” You ask him as you bat your eyelashes. It’s been since you were 18 that you decided you wanted the attention of older men. The guys your age just couldn’t compete. They left you feeling unsatisfied with their fibs of knowing how to please a woman. Most of them couldn’t even locate the clitoris, let alone give a woman an orgasm. “You know what we’re going to do today, princess.” His hands wrap themselves around your waist as he places wet kisses all over your neck. You squeal softly at his attention."

# # 5. Preprocess the new text
# processed_text = regeks(new_text)

# # 6. Transform the preprocessed text using TF-IDF
# new_text_features = tfidf.transform([processed_text]).toarray()

# # 7. Make the prediction
# prediction = model.predict(new_text_features)

# # 8. Get the predicted category (assuming prediction is directly the category label)
# predicted_category = prediction

# # 9. Print the result
# print(f"Predicted Category: {predicted_category}")


Predicted Category: ['Porn']
